### ISSUE TITLE
Indentation introduces by MPTT is lost

### ISSUE THREAD

**Issue by ecstaticpeon** [django-cms/djangocms-admin-style#15]
MPTTModelAdmin (0.6.0) indents children using an inline padding-left on the th. However this is overwritten by djangocms-admin-style's CSS (0.2.2) with:

``` css
.module table th {
    padding: 2px 5px !important;
    [...]
}
```
