### ISSUE TITLE
CSS rule hides picture upload widget in blog

### ISSUE THREAD

**Issue by MacLake** [django-cms/djangocms-admin-style#522]
I use django-cms==3.11.5. With the CSS rules of djangocms-admin-style==3.3.0 the picture upload widget in the blog entries in djangocms-blog==2.0.7 are hidden.

The culprit is in djangocms_admin_style/sass/components/_forms.scss:

```scss
form {
    margin-bottom: 20px;
    padding: 25px 25px;
    background-color: $white;
    box-shadow: $base-box-shadow;
    fieldset, .inline-group {
        width: 80%;
    }

    // Newer Django admin styles use flexbox, we do not
    .flex-container {
        display: block;
        margin-right: 20px;
    }
    .flex-container.form-multiline {
        display: flex;
        margin-right: 0;
        div.fieldBox {
            display: block;
            //margin-right: 0;
        }
        div:has(div.hidden) {
            display: none;
        }
    }
/* … */
}
```

`display: none;`  hides the picture widget.

I have created a [fix in my fork](https://github.com/MacLake/djangocms-admin-style/commit/5e0802cf4d9105bd6bfc485899c3c8baedca7e92), which just removes a `display: hidden;` but I don’t know if it breaks anything else, because I don’t know the idea of this rule.
